spring:
  application:
    name: history-excerptor
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT:5432}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

schema:
  name: public
  historyTableSuffix: _hst

excerpt:
  url: ${EXCERPT_URL}
  accessToken: ${EXCERPT_TOKEN}
  statusCheck:
    maxAttempts: 10

dso:
  url: ${DSO_URL}

request-signature-ceph:
  http-endpoint: ${REQUEST_SIGNATURE_CEPH_HTTP_ENDPOINT}
  bucket: ${REQUEST_SIGNATURE_CEPH_BUCKET_NAME}
  access-key: ${REQUEST_SIGNATURE_CEPH_ACCESS_KEY}
  secret-key: ${REQUEST_SIGNATURE_CEPH_SECRET_KEY}

openshift:
  enabled: true
  namespace: ${OPENSHIFT_NAMESPACE}
  parentJob:
    name: ${OPENSHIFT_JOB}
    resultField: ${OPENSHIFT_RESULT_FIELD}